### ISSUE TITLE
Request for Dataset Using Google Drive etc.

### ISSUE THREAD

**Issue by Frost24K** [gmberton/EarthLoc#1]
Hi,

Great work! However, my network connection is too unstable to use the Python script for downloading the dataset. Could you please provide a compressed file containing both the query and reference images, and upload it to Google Drive or another file-sharing service? I would greatly appreciate it if you could do this.

Thank you so much!

**Comment by gmberton** [comment]
Hi, you can run the 
```
python data/database_downloader.py
python data/queries_downloader.py
```
and if some issue happens during the download, you can run them again and the download will restart from where it left, because the script downloads images one at a time, and it takes care of network issues (there will be no images that are only half-downloaded).
If I create compressed file(s) it will be more complicate, because people would have to check that the cksums are correct, and it will make it more complicate for people with slow connection.
Let me know if re-starting the script works for you!

**Comment by Frost24K** [comment]
Hi,

Thank you for your quick response. The actual problem is that the download speed and connection are too poor, which has forced me to retry multiple times. Nevertheless, thank you for addressing this issue. I will try to download it using these scripts.

Best！
