### ISSUE TITLE
apply the EarthLoc for uav and satellite images query

### ISSUE THREAD

**Issue by songkemail** [gmberton/EarthLoc#2]
Hi, gmberton, another great job!
the EarthLoc is trained on low res database image from level 9 to 11, can I apply the EarthLoc for high res satellite images as database to query uav images? collect the XYZ global tiles which size is 256*256 from level 16 to 18 as database

**Comment by gmberton** [comment]
Hi thank you!
Do you mean that you would like to use it directly with our weights, or would you like to train it on higher res images?
I think it might not work too well with the our trained weights because the domain is quite different, but it would be interesting to try it. But if trained on high res images, I think it should work well but I never tried

**Comment by songkemail** [comment]
yeah, thank you,  I'll train it on higher res images.
