### ISSUE TITLE
Error 403 when trying to download dataset

### ISSUE THREAD

**Issue by dakloepfer** [gmberton/EarthLoc#3]
Very cool paper! When trying to download the dataset with the download script, the download recently got stuck at some point, only giving errors like 
`Couldn't download https://s2maps-tiles.eu/wmts?layer=s2cloudless-2020_3857&style=default&tilematrixset=GoogleMapsCompatible&Service=WMTS&Request=GetTile&Version=1.0.0&Format=image%2Fjpeg&TileMatrix=11&TileCol=1812&TileRow=694 due to HTTP Error 403: Forbidden, will retry in 10 seconds`. 

`curl "https://s2maps-tiles.eu/wmts?layer=s2cloudless-2020_3857&style=default&tilematrixset=GoogleMapsCompatible&Service=WMTS&Request=GetTile&Version=1.0.0&Format=image%2Fjpeg&TileMatrix=11&TileCol=1812&TileRow=694"` also gives an 403 Forbidden: Request forbidden by administrative rules. error, so this seems to be a problem with the dataset host. 

Would you be able to reset these administrative rules, or would you be able to provide access to the dataset through another channel?

**Comment by gmberton** [comment]
Hi @dakloepfer it seems that now those tiles are not available for download anymore, I really don't know why. Also, I'm not sure if I can distribute them due to possible licensing issues (I'm guessing if they blocked access they must have some reason). Hopefully this is a temporary issue, but there is nothing I can do to make sure they release those data

**Comment by gmberton** [comment]
I have now uploaded the dataset to a server and it can be downloaded with
```
rsync -rhz --info=progress2 --ignore-existing rsync://vandaldata.polito.it/sf_xl/EarthLoc/data .
```

I've also updated the README to mirror the changes
